### ISSUE TITLE
Incorrect modified file indicator

### ISSUE THREAD

**Issue by pjg** [lambdalisue/vim-suda#1]
I'm using VimR.

When I save current file using `:w suda://%` the modified file indicator stays the same, i.e. it shows that the file has been modified. It also prompts me to save the file when I try to quit VimR, while it should not.

**Comment by tracyone** [comment]
i can repoduced in vim too.

**Comment by lambdalisue** [comment]
Ah, I got it. I'll fix it thanks 👍

**Comment by lambdalisue** [comment]
Fixed

**Comment by pjg** [comment]
Works now! Thanks!
