### ISSUE TITLE
Make suda:// buffer more secure

### ISSUE THREAD

**Issue by mox-mox** [lambdalisue/vim-suda#14]
When opening files that only root can read using `suda`, nvim will still create a world-readable backup file. For files containing sensitive information, this is highly undesirable.

**Comment by lambdalisue** [comment]
Good point. I'll consider the way once I get time. Well, PR is really welcome as well 👍

**Comment by lambdalisue** [comment]
`noswapfile` as well.

Thanks to @ichizok, https://vim-jp.slack.com/archives/C03C4RC9F/p1558601882079900

**Comment by lambdalisue** [comment]
- [ ] `nobackup`
- [ ] `noswapfile`
- [ ] `noundofile`
- [ ] `bufhidden=wipe`
    - Not sure if it should be because `<C-o>/<C-i>` does not work with `wipe`

Anything else?
