### ISSUE TITLE
Why do you set bufhidden to `delete`?

### ISSUE THREAD

**Issue by doronbehar** [lambdalisue/vim-suda#19]
Hey,

I noticed you do this:

https://github.com/lambdalisue/suda.vim/blob/b867074b30f623ccb81a0bb8d1b74a6d0fafd160/autoload/suda.vim#L159

Commit: https://github.com/lambdalisue/suda.vim/commit/f70355e444baa8700d4c1fc91cc0f5b6896855a3 .

This really bothers me when I open multiple files and some are with the `suda://` prefix and switch between the buffers, the `suda://` buffers just disappear.

In order to mitigate this behavior I've commented this line on my clone. Just wondering what was the rational behind this?

**Comment by lambdalisue** [comment]
Security reason. We need to wipe out the content.

**Comment by doronbehar** [comment]
From my experience, programs which open files with sensitive information, e.g [gopass](https://github.com/gopasspw/gopass) , [suggest](https://github.com/gopasspw/gopass/blob/master/docs/setup.md#securing-your-editor) using only `nobackup`, `noswapfile` and `noundofile` which you are already setting. 

TBH, I just don't see how this is related to security - when the editor quits, the buffer is deleted - end of story right? There shouldn't be any need to delete the buffer even if one switches between a `suda://` buffer and another buffer.

**Comment by lambdalisue** [comment]
Without `bufhidden=delete`, `<C-o>/<C-i>` works and the content may be shown by chance right? I'd tried to prevent that behavior. But well, I'm not sure if it should be.

**Comment by doronbehar** [comment]
Hmm, I understand the concern yet I don't think this should be suda's responsibility.

Please consider this concern, versus the usability issue I described in my [first comment](https://github.com/lambdalisue/suda.vim/issues/19#issue-464164981) - Users who use buffers and therefor may come about editing multiple files simultaneously, switch between them etc., are surprised every time the `suda://` buffer is deleted. TBH it is rather annoying.

I think a user who is not even aware of the 'buffers' feature, is probably someone who just edits one file at a time and therefor it wouldn't make a difference for him. My opinion is that _users_ should take responsibility to their buffers, not _plugins_.

**Comment by lambdalisue** [comment]
> I think a user who is not even aware of the 'buffers' feature, is probably someone who just edits one file at a time and therefor it wouldn't make a difference for him. My opinion is that users should take responsibility to their buffers, not plugins.

Make sense. I'll change the current behavior 👍

**Comment by lambdalisue** [comment]
Done. Thanks for the suggestion 🥇

**Comment by doronbehar** [comment]
Thank you for caring, It was my pleasure :).
