### ISSUE TITLE
Can I reuse your code in another plugin?

### ISSUE THREAD

**Issue by zhujinxuan** [lambdalisue/vim-suda#2]
Hi, thank you for your great effort in providing sudo features.

I am trying to provide `sudo write` logic in SpaceVim (https://github.com/SpaceVim/SpaceVim/pull/1539). But for some reason I cannot import the plugin directly. May I have your permit of using your code in the PR?

**Comment by lambdalisue** [comment]
> But for some reason I cannot import the plugin directly.

I'd love to know why.

**Comment by zhujinxuan** [comment]
Thank you a lot.  I fix that by your suggestion (let g:suda_startup = 0 )
