### ISSUE TITLE
Make a prompt title configurable

### ISSUE THREAD

**Issue by Dupond** [lambdalisue/vim-suda#21]
Hi,

Thank you for this great plugin. I use it with neovim, and it works just fine !

Would it be possible to have a setting to localize the "Password:" prompt ? Maybe something like :
`let g:suda#password_prompt = 'Mot de passe :'`

Thanks !

**Comment by lambdalisue** [comment]
Technically it's quite easy but I'm not really welcome while I don't want to mess up this small plugin by considering i18n. Thus, I'm sorry but it won't be fixed.

**Comment by lambdalisue** [comment]
Wait. If the issue title is "Make a prompt configurable" then I'm OK and I think you are satisfied with that right?

PR is welcome. Just use `g:suda#password_prompt` on https://github.com/lambdalisue/suda.vim/blob/master/autoload/suda.vim#L40

**Comment by Dupond** [comment]
It would be just fine : that's what I meant in my first message.

Unfortunately, I don't know how to program myself, and thus can't provide a PR.

**Comment by lambdalisue** [comment]
Then try #22

**Comment by Dupond** [comment]
Perfect ! Thank you very much !

**Comment by Dupond** [comment]
Thank you for having merged this PR ! It works great.

Is there a reason why, under Linux, the password is not asked "in the Linux way", that is to say without displaying any character ?

**Comment by lambdalisue** [comment]
No. Vim does that.

**Comment by Dupond** [comment]
Oh, OK. Thanx for the information !
