### ISSUE TITLE
Smart edit prevents nvim -d from working

### ISSUE THREAD

**Issue by Dupond** [lambdalisue/vim-suda#23]
Hello !

When `let g:suda_smart_edit = 1` is set in my `init.vim` file, I can't use `nvim -d` to display a diff between 2 read-only files (or 1 read-only file, and 1 writable file).

Without the option set, everything is fine.

Thanx for the help,
Best regards,
Dupond

**Comment by lambdalisue** [comment]
I have no idea about `nvim -d` so please provide details.

**Comment by psliwka** [comment]
`nvim -d` is basically `vimdiff` equivalent.

**Comment by lambdalisue** [comment]
Well, I'm sorry but I'm not esp so closed. Please feel free to re-open or create a new one with detailed information about the issue and reproduction procedure.

**Comment by psliwka** [comment]
This is not my business at all (in fact, I just came across this issue by accident), but shouldn't this be marked as 'help wanted' instead of just closing?
