### ISSUE TITLE
make it work with persistent undo

### ISSUE THREAD

**Issue by nycex** [lambdalisue/vim-suda#25]
i have `set undofile undodir=~/.local/share/nvim/undo` set in my nvim config but still persistent undo does not work with files in smart edit or saved via `:w sudoa://%`. It would be great if that would work though, since that is the strongest reason why I don't use sudoedit.

**Comment by lambdalisue** [comment]
I'm sorry but it comes by security reason. suda does NOT allow backup file, swap file, and undo file otherwise these files may be written in readable permission.

https://github.com/lambdalisue/suda.vim/blob/master/autoload/suda.vim#L158

**Comment by nycex** [comment]
Well you could enable it at least for files the current user is able to read but not write.

**Comment by lambdalisue** [comment]
I'm not sure if Vim create backup/swap/undo files in 600.

If you desire, I think you can use `BufReadPost` autocmd to overwrite that setting.

**Comment by nycex** [comment]
That doesn't seem to work, I added
`autocmd BufReadPost * set undofile`
but I still have no persistent undo. Also, it's not really about smart edit, I use just the saving normally, but it also doesn't work with smart edit.

**Comment by lambdalisue** [comment]
Hum... then I've no idea sorry.

**Comment by lambdalisue** [comment]
https://github.com/lambdalisue/suda.vim/pull/26

I'm sure now that persistent undo becomes a security hole thus the feature will never be acceptable. I'm sorry for the inconvenience.

**Comment by sevmonster** [comment]
I have implemented this with the following Vim script:

```vim
" re-enable backup, swap, undo for suda smart-edit buffers
" https://github.com/lambdalisue/vim-suda/issues/25
function! s:SudaSettingsSave()
    " save opts for buf before wiping it out
    if exists('b:suda_smart_edit_checked')
        let w:sev_suda_swapfile = &swapfile
        let w:sev_suda_undofile = &undofile
    else
        unlet! w:sev_suda_swapfile w:sev_suda_undofile
    endif
endfunction
function! s:SudaSettingsRestore()
    " restore opts from wiped out file buf
    if exists('w:sev_suda_swapfile')
        if w:sev_suda_swapfile
            try
                setlocal swapfile
            catch
                " ignore swapfile errors, they should have been shown already
                echohl ErrorMsg
                echomsg printf('[suda] swapfile: %s', v:exception)
                echohl None
            endtry
        endif
        unlet w:sev_suda_swapfile
    endif
    if exists('w:sev_suda_undofile')
        if w:sev_suda_undofile
            setlocal undofile
        endif
        unlet w:sev_suda_undofile
    endif
endfunction
function! s:SudaProcessUndo(cmd)
    " re-implement undofile since vim can only find fs path buffers' undofiles
    let p = expand('<afile>')[7:]
    if has('win32') || !&undofile
        return
    endif
    let p = resolve(p)
    " XXX: comments are from :help backupdir to mark implementation details
    let x = &undodir
    " For backwards compatibility with Vim version 3.0 a '>' at the start
    " of the option is removed.
    if stridx(x, '>') == 0
        let x = x[1:]
    endif
    " To include a comma in a directory name precede it with a backslash.
    for u in split(x, '\v\\@1<!,')
        " Spaces after the comma are ignored, other spaces are considered part
        " of the directory name.
        let u = trim(u, ' ', 1)
        " To have a space at the start of a directory name, precede it with a
        " backslash.
        if stridx(u, '\ ') == 0
            let u = u[1:]
        endif
        " Empty means that no backup file will be created.
        if empty(u)
            continue
        elseif u == '.'
            " A directory "." means to put the backup file in the same
            " directory as the edited file.
            let d = fnamemodify(p, ':p:h')
        elseif stridx(u, './') == 0
            " A directory starting with "./" (or ".\" for MS-Windows) means to
            " put the backup file relative to where the edited file is.
            let d = printf('%s%s', fnamemodify(p, ':p:h'), expand(u))
        else
            let d = u
        endif
        " XXX: env vars are not expanded, and backslashes are not handled...
        if u == '.'
            let f = printf('.%s.un~', fnamemodify(p, ':t'))
        else
            let f = fnamemodify(p, ':p:gs?/?%?')
        endif
        " A directory name may end in an '/'.
        let d = trim(d, '/', 2)
        if !isdirectory(d)
            continue
        endif
        try
            execute printf('%s %s/%s', a:cmd, fnameescape(d), fnameescape(f))
            break
        catch
            continue
        endtry
    endfor
endfunction
autocmd BufAdd suda://* call s:SudaSettingsSave()
autocmd BufReadPost suda://* call s:SudaSettingsRestore()
autocmd BufReadPost suda://* call s:SudaProcessUndo('silent! rundo')
autocmd BufWritePost suda://* call s:SudaProcessUndo('wundo!')

```
https://git.sev.monster/~sev/dotfiles.git/blob/b758c1000aa81a146633112bdf8a54e8f5efbbc9:/etc/vim/.vimrc#l179

This works for all `suda://` buffers, including those reopened with `g:suda_smart_edit`.

Undofile loading/saving had to be done manually since it doesn't seem to be loaded with `:read` which `suda#read` uses for readable files—similar situation for writing. (Technically this would also work for `sudo`-read files, but I disable it for user-unreadable files for security reasons. You can always remove that restriction if you know what you're doing.)

No backup support yet, I may do that eventually. Similar functionality as for `undofile` will need to be added when saving `suda://` buffers.

**Comment by alcroito** [comment]
I agree it would be great if this were an opt-in option. The README could just mention the potential security implications.
