### ISSUE TITLE
suda_smart_edit too slow

### ISSUE THREAD

**Issue by v6cc** [lambdalisue/vim-suda#30]
I like use `let g:suda_smart_edit = 1`

but when open a file (1000-2000 lines) , always block cursor 5 seconds or more

Is there a way to speed up? or disable it for some filetypes

**Comment by lambdalisue** [comment]
maybe we need to add some cache mech. to https://github.com/lambdalisue/suda.vim/blob/master/autoload/suda.vim#L229-L239

Could you try if removing the above block temporarily fix the performance issue?

**Comment by v6cc** [comment]
> maybe we need to add some cache mech. to

Not changed, I tried open a small file then switch to a big file, it takes 5 seconds .

then  use ctrl+o ,  but ctrl+i  still need same time

**Comment by lambdalisue** [comment]
So what exact size for "small" or "big" in your situation?

**Comment by v6cc** [comment]
> So what exact size for "small" or "big" in your situation?

`/etc/resolv.conf`              have  three lines

`/usr/lib/go/src/fmt/print.go`   have 1176 lines

**Comment by lambdalisue** [comment]
Hum... that's not big (I imaged like 1 GB files or so on.)

Well what happens if

1. Copy `/usr/lib/go/src/fmt/print.go` as `/usr/lib/go/src/fmt/print.txt`
2. Open `/usr/lib/go/src/fmt/print.txt` with suda.vim

**Comment by v6cc** [comment]
> Hum... that's not big (I imaged like 1 GB files or so on.)
> 
> Well what happens if
> 
> 1. Copy `/usr/lib/go/src/fmt/print.go` as `/usr/lib/go/src/fmt/print.txt`
> 2. Open `/usr/lib/go/src/fmt/print.txt` with suda.vim

open /usr/lib/go/src/fmt/print.txt not block

**Comment by lambdalisue** [comment]
Then probably it's not suda's problem. It's on Go plugin.

**Comment by zdmgmail** [comment]
> Then probably it's not suda's problem. It's on Go plugin.

I tried just have one plug  : suda.vim , still this problem... what go plugin

**Comment by v6cc** [comment]
> Then probably it's not suda's problem. It's on Go plugin.

`set foldmethod=syntax` I found this line cause the problem..

this line not in plugin, Is there a way to solve this?

I tried no other plugin, just `suda.vim`

**Comment by v6cc** [comment]
> Then probably it's not suda's problem. It's on Go plugin.

init.vim

```
call plug#begin('~/.config/nvim/plugged')
Plug 'lambdalisue/suda.vim'
call  plug#end()

let g:suda#prefix = ['suda://', 'sudo://', '_://']
let g:suda_smart_edit = 1

set foldmethod=syntax
```
