### ISSUE TITLE
doas support?

### ISSUE THREAD

**Issue by ghost** [lambdalisue/vim-suda#40]
Would you please support doas if you like?

**Comment by subterfugue** [comment]
I agree with this. 
```
suda] sudo: invalid option -- 'p'
[suda] usage: doas [-Lns] [-C config] [-u user] command [args]
```
This is what I receive after inputting my password when running `:SudaWrite`, I don't think it'd take much to add it in.

**Comment by AnasR7** [comment]
please make this hapeend

**Comment by not-a-robot06** [comment]
Maybe make it use su instead, as that's installed on most if not all systems as far as I know. For example, makepkg uses su if sudo is not found...

**Comment by lambdalisue** [comment]
Oops. I'm sorry I didn't notice this request. Well, I have no idea what "doas" and I have no idea what to do to support it.

**Comment by ghost** [comment]
doas is alternative to sudo
https://wiki.archlinux.org/title/Doas
sudo has the -p option, but doas does not, so symbolic links will not work
もしよければ私に対して日本語を話してください

**Comment by subterfugue** [comment]
I've already cloned this project and tried to work on it, but I've hit a "roadblock,", doas doesn't have the flag that sudo does to pass the password to, so you're probably going to use expect or socat or something like that. It's likely not going to be that hard, but maybe it'd be more efficient if it uses something that's essentially really light and exists on all systems that isn't exactly replacable, like maybe the `su` util or something more tightly-knit, I'm unsure. Do as you wish, and thank you for listening!

**Comment by lambdalisue** [comment]
Probably, I'm not going to support `doas` or `su` in suda.vim (by myself) while suda.vim has technical limitation (#34). Instead, maybe I'll create a new fresh plugin for handle #34 and then I'll consider to support `doas` and/or `su`.

> もしよければ私に対して日本語を話してください

I'm sorry but it seems some people interested in this topic so I prefer to discuss it with English.

**Comment by aarondill** [comment]
This issue is fixed by #58

**Comment by acid-bong** [comment]
@aarondill it's not, sudo-specific `-p` and `-S` flags are still used by the plugin

**Comment by aarondill** [comment]
@lambdalisue 
Line 18 of autoload/suda.vim needs to be changed to fully support doas (when a password is needed)

**Comment by aarondill** [comment]
@acid-bong I've looked at the source for doas, and it seems there's no way to pass a password to stdin, instead of requiring a terminal. Changing line 18 (see above) would allow it to work with any programs which read from stdin, but if it attempts to open a tty (like doas), we can only support the no password version. 

I'm not certain of any tools for this purpose that do except through stdin, but the above mentioned change would allow them to work by default (after setting the executable variable)

**Comment by acid-bong** [comment]
@aarondill a possible solution could be found somewhere in Emacs' [`tramp.el`](https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/net/tramp.el?h=emacs-28) (for current stable branch, emacs-28), doas is one of the preconfigured privilege elevation tools in it. I know it does work flawlessly* (except when your default shell is zsh, but that's a different issue), but i'm yet to find out how it passes the password, because it doesn't use -S for sudo

**Comment by lambdalisue** [comment]
I still don't use `doas` so it's a bit hard for me to support it while I've no idea what I need to do so PRs are very welcome to support it.

**Comment by aarondill** [comment]
> @aarondill a possible solution could be found somewhere in Emacs' [`tramp.el`](https://git.savannah.gnu.org/cgit/emacs.git/tree/lisp/net/tramp.el?h=emacs-28) (for current stable branch, emacs-28), doas is one of the preconfigured privilege elevation tools in it. I know it does work flawlessly* (except when your default shell is zsh, but that's a different issue), but i'm yet to find out how it passes the password, because it doesn't use -S for sudo

Sadly, I can't for the life of me read lisp, especially when it's *that* abstracted. If you can figure it out, please let me know. My guess would be that emacs allows commands to open a tty when executing (like `vim` did), which nvim doesn't (I'm likely misunderstanding the root issue, but still), which is the original reason this plugin was necessary.

**Comment by aarondill** [comment]
With the merging of #60, you can now use `doas` *only* with `nopass` configured!

**Comment by mainrs** [comment]
Posting here so subscribers get notified. You can use the [expect](https://repology.org/project/expect/versions) package to make this work with `doas`. Save the following script to `~/.local/bin/nvim-doas`.

```sh
#!/usr/bin/expect --

# Get the arguments passed to the script.
set args [lrange $argv 0 end]

# Calls doas and passes all arguments to it as they have been passed to this script.
spawn doas {*}$args

# Waits until the process finishes.
expect eof
```

Then call `vim.g['suda#executable'] = 'nvim-doas'`. [Credit](https://github.com/Duncaen/OpenDoas/issues/21#issuecomment-854727152).

The above works with fingerprint sensors only I think. Can probably be made to work with password, too.

### I DO NOT know the security implications of this. I don't know if it would be possible to overtake some buffer to make you execute arbitrary commands as super user. Use with caution.
