### ISSUE TITLE
suda doesn't work in nvim in nixos

### ISSUE THREAD

**Issue by tex** [lambdalisue/vim-suda#41]
![nvim_nixos_suda_error](https://user-images.githubusercontent.com/27386/112055099-b9778c00-8b56-11eb-9441-8725f09ea2d0.png)

It used to work, but now it is not. No idea what has changed. Any ideas what to try?

**Comment by zeertzjq** [comment]
This seems to be a problem with `shellescape()`. I guess you are using `xonsh`. Does this problem still occur if you `:set  shell=/bin/sh`?

**Comment by tex** [comment]
Bingo! Thanks @zeertzjq. And I am very sorry I forget to tell about `xonsh`. Yes I am using it. I didn't realized it gets propagated into what `nvim` uses internally.

**Comment by tex** [comment]
And yes, after setting shell to `sh` the problem goes away and `suda` works as expected.

**Comment by tex** [comment]
Feel free to close this issue if you think `suda` does not need any change. I am fine with adding the shell setting into my config. Guess it won't have any other side issues.
