### ISSUE TITLE
Prompt to re-read file after SudaWrite

### ISSUE THREAD

**Issue by UnkwUsr** [lambdalisue/vim-suda#43]
This can be done by simply calling `:checktime` after SudaWrite.
I don't know if we should add this call elsewhere, because I only use this one command. So I created an issue instead of a pull request.
![image](https://user-images.githubusercontent.com/49063932/113597557-8ea43200-9644-11eb-8a4f-d1ea50185ca9.png)

**Comment by lambdalisue** [comment]
I'm sorry for late reply and I didn't know `checktime`. It seems quite useful thanks 👍

**Comment by aarondill** [comment]
this was fixed by #59 and can now be closed 😃
