### ISSUE TITLE
[suda] dd: failed to open 'suda:///etc/i3blocks.conf': No Such file or directory

### ISSUE THREAD

**Issue by ShaneWiker** [lambdalisue/vim-suda#45]
SudaWrite is working well for me with some files, but I get this error when saving some files despite having no issues saving them with :w!

What's causing this when the file does exist?

This is how I'm using the command:
`nnoremap <Leader>ms :SudaWrite<CR>`

**Comment by lambdalisue** [comment]
I've never seen this error before so I need to reproduce the situation in my environment. Please provide a minimal vimrc (less than 20 lines) and step by step procedure to reproduce the situation.

**Comment by zeertzjq** [comment]
Only one of `:w` and `SudaWrite` may work.
