### ISSUE TITLE
suda does not work when `sudo` command is aliased to something else

### ISSUE THREAD

**Issue by alexmozaidze** [lambdalisue/vim-suda#57]
I have an alias
```bash
alias sudo="doas"
```
And when trying to write a buffer that uses `suda://` it invokes *`doas`* instead of `sudo`.

# Solution 

Use `env`:
```bash
/usr/bin/env sudo -p some_arguments
```

**NOTE**: this might not work in windows.

**Comment by lambdalisue** [comment]
@alexmozaidze
In my opinion, It's not bug of suda.vim because YOU aliased `sudo` to something else.
But I'd like to support such case so I added `g:suda#executable` option on #58. You can set absolute path of `sudo` command to that variable. Could you try if #58 solves your issue.

**Comment by alexmozaidze** [comment]
Is nice. I like this compromise better than just hardcoding it.

**Comment by alexmozaidze** [comment]
Now that I think about it, I can now do a check:
```lua
if command_exists "doas" then
  vim.g["suda#executable"] = "/usr/bin/env -- doas"
  vim.g["suda#nopass"] = 1
else
  vim.g["suda#executable"] = "/usr/bin/env -- sudo"
  vim.g["suda#nopass"] = 0
end
```
This allows for both `doas` and `sudo` support, though, `doas` must be configured to not require a password.
