### ISSUE TITLE
What effect does `g:suda_startup` has?

### ISSUE THREAD

**Issue by doronbehar** [lambdalisue/vim-suda#6]
I would like to contribute to this plugin a new setting that will enable automatically writing with `suda` when no permissions to the current user are available. I was reading the code which is written very well and clear, yet I didn't understand the effect `g:suda_startup` has. I've tested it and whether it set or not, `nvim suda:///etc/bla` asks for a password.

Thanks.

**Comment by lambdalisue** [comment]
That is used in [plugin/suda.vim](https://github.com/lambdalisue/suda.vim/blob/master/plugin/suda.vim#L6) to call `suda#init()`.

> I've tested it and whether it set or not, nvim suda:///etc/bla asks for a password.

It should be `let g:suda_startup = 0` to disable that feature instead while the default value is `1` instead of `0` when there is no such variable.

**Comment by doronbehar** [comment]
Got it, thanks!
