### ISSUE TITLE
Cannot activate suda_smart_edit

### ISSUE THREAD

**Issue by JostBrand** [lambdalisue/vim-suda#62]
OS: Linux

Lazy install:
`require("lazy").setup({"lambdalisue/suda.vim"})`

Parameter set:
`vim.g.suda_smart_edit = 1`

If I copy the code from the source it works:

```
vim.api.nvim_exec([[
    augroup suda_smart_edit
    autocmd!
    autocmd BufEnter * nested call suda#BufEnter()
  augroup end]],false)
```

**Comment by lambdalisue** [comment]
`g:suda_smart_edit` **must** be configured **before** this plugin is loaded.

**Comment by JostBrand** [comment]
Perfect, thank you!

**Comment by samos667** [comment]
It's supposed to work by this way ? (I use AstroNvim)

```
{
    "lambdalisue/suda.vim",
    event = "VeryLazy",
    init = function() vim.g.suda_smart_edit = 1 end,
  },
```

I'm cannot manage to get this fonction work. When I open /etc/hosts the file is not modifiable.

**Comment by lambdalisue** [comment]
I'm not sure, but I guess that `g:suda_smart_edit` was configured after the plugin loaded with that configuration. I have no experience with AstroNvim, so you should ask how to configure that variable in AstroNvim or on StackOverflow.
