### ISSUE TITLE
suda:///the/path/of/file will disable language server's jumpDefinition

### ISSUE THREAD

**Issue by Freed-Wu** [lambdalisue/vim-suda#63]
When open `suda:///usr/include/XXX.h`, language server (clangd) cannot execute jumpDefinition. Change `suda:///usr/include/XXX.h` to `/usr/include/XXX.h` can fix this problem. Is there any problem to fix it?

**Comment by lambdalisue** [comment]
I don't get but do you mean that suda should handle `/usr/include/XXX.h` buffer instead of `suda:///usr/include/XXX.h`? Then, answer is no unfortunately.

**Comment by Freed-Wu** [comment]
It should be because language server cannot handle `suda://`. I see. Thanks!
