### ISSUE TITLE
Empty "suda:" directory created in $HOME on write

### ISSUE THREAD

**Issue by acamso** [lambdalisue/vim-suda#64]
When saving a `suda://` file, the file is saved correctly but also creates an empty directory tree in `$HOME`.

For example, saving `suda:///home/<user>/.config/file` creates `suda:/home/<user>`

This is with all defaults, `g:suda_smart_edit = 1`, and on the latest commit `8b0fc3711760195aba104e2d190cff9af8267052`

Thank you!

**Comment by lambdalisue** [comment]
Could you provide a minimal vimrc that only have `suda.vim` in `runtimepath`?

**Comment by acamso** [comment]
I debugged it and the culprit was an auto-command for creating non-existing directories before saving:

`au BufWritePre * call mkdir(expand("<afile>:p:h"), "p")`

I modified it to the following:

`au BufWritePre * call mkdir(substitute(expand("<afile>:p:h"), "^suda://", "", ""), "p")`

Cheers
