### ISSUE TITLE
RFC on Idea: Making suda completly automatic

### ISSUE THREAD

**Issue by doronbehar** [lambdalisue/vim-suda#7]
Continuing from #6, I would like to suggest a PR for `suda.vim` that will make it completely automatic. After reading the code, I've realized that it'd require to change it's internals a lot, therefor I would like to ask for comments on the idea:

What if `suda.vim` wouldn't work only on files with the `suda://` prefix and it would automatically detect if there are read and write permissions and ask for a password for writing and reading it accordingly? For example:
If a normal user would run the command `nvim /etc/sudoers`, the following will happen:
- `nvim` (with `suda.vim` installed) will attempt to read the requested file.
- It will find out that read permissions are not available.
- Using the user's `sudo` password, It would put the contents of `suda:///etc/sudoers` in the current buffer.
- It will set an `autocmd` that will make every write operation write to `suda:///etc/sudoers` and not `/etc/sudoers` and afterwards update the contents of the `/etc/sudoers` buffer with the updated content.

On the other hand, when only write permission is missing, only the last action will be performed.

I'd love to hear your thoughts before I'll begin working on this,
Thanks.

**Comment by lambdalisue** [comment]
Interesting. I'd love to see the PR.

My thought for the idea are

1. I don't think the internal code need to be changed a lot. Adding extra BufReadPre and FileReadPre seems enough (not confirme)
2. The behavior need to be optional while some users would prefer explicit way
3. Using BufWritePre/FileWritePre may help for writing a file which only miss a write permission

Thanks for your idea :-]

**Comment by doronbehar** [comment]
Hello again @lambdalisue,

I've started working on this PR and I have already wrote a nice function that returns if `sudo` is needed at all for a given file, it considers if we know it exists and if we can read it's parent directories contents and their permissions.

I'm not sure whether a new configuration variable should be introduced or whether we should call `suda#init()` differently according to a `g:suda#prefix` which would be empty? My vision is that it would be much more elegant if a user wanting to change the prefix or make the plugin act automatically would add a single command in his `init.vim`, something like this:

```vim
call suda#init('sudo:*')
```

I must say that I find the current relationship between `g:suda#prefix` and `suda#init()` rather complicated. For example, IMO, having to write 2 lines just to change the prefix makes things a little bit confusing.

What do you think about this patch:
```diff
 autoload/suda.vim | 16 ++++++----------
 doc/suda.txt      |  5 ++---
 plugin/suda.vim   |  2 +-
 3 files changed, 9 insertions(+), 14 deletions(-)

diff --git c/autoload/suda.vim i/autoload/suda.vim
index fa623d9..5e0a3f4 100644
--- c/autoload/suda.vim
+++ i/autoload/suda.vim
@@ -1,11 +1,11 @@
-function! suda#init(...) abort
-  let pat = a:0 ? a:1 : printf('%s*', g:suda#prefix)
+function! suda#init(pat) abort
+  let g:suda#prefix = a:pat[:-2]
   augroup suda_internal
     autocmd! *
-    execute printf('autocmd BufReadCmd %s call suda#BufReadCmd()', pat)
-    execute printf('autocmd FileReadCmd %s call suda#FileReadCmd()', pat)
-    execute printf('autocmd BufWriteCmd %s call suda#BufWriteCmd()', pat)
-    execute printf('autocmd FileWriteCmd %s call suda#FileWriteCmd()', pat)
+    execute printf('autocmd BufReadCmd %s call suda#BufReadCmd()', a:pat)
+    execute printf('autocmd FileReadCmd %s call suda#FileReadCmd()', a:pat)
+    execute printf('autocmd BufWriteCmd %s call suda#BufWriteCmd()', a:pat)
+    execute printf('autocmd FileWriteCmd %s call suda#FileWriteCmd()', a:pat)
   augroup END
 endfunction
 
@@ -247,7 +247,3 @@ function! s:doautocmd(name) abort
         \ fnameescape(expand('<afile>'))
         \)
 endfunction
-
-
-" Configure
-let g:suda#prefix = get(g:, 'suda#prefix', 'suda://')
diff --git c/doc/suda.txt i/doc/suda.txt
index d0d28d4..7aead83 100644
--- c/doc/suda.txt
+++ i/doc/suda.txt
@@ -117,10 +117,9 @@ g:suda#prefix
 QUESTIONS					*suda-questions*
 
 Q. How to use "sudo:" instead of "suda://" like "sudo.vim".
-A. Use |g:suda#prefix|| like below.
+A. Call |suda#init| with a pattern of your choice.
 >
-	let g:suda#prefix = 'sudo:'
-	call suda#init('sudo:*,sudo:*/*')
+	call suda#init('sudo:*')
 <
 Q. How to use SudoRead/SudoWrite command like "sudo.vim".
 A. Write the following scripts in your |vimrc|.
diff --git c/plugin/suda.vim i/plugin/suda.vim
index 9ed1c74..e7187ae 100644
--- c/plugin/suda.vim
+++ i/plugin/suda.vim
@@ -4,5 +4,5 @@ endif
 let g:loaded_suda = 1
 
 if get(g:, 'suda_startup', 1)
-  call suda#init()
+  call suda#init('suda://*')
 endif
```

**Comment by lambdalisue** [comment]
You said "make it completely automatic", mean that users with your optional feature actually do not need to use `suda://` prefix or whatever.
So I think you don't need to care about `g:suda#prefix`, just overwrite the default value forcedly.

```vim
" autoload/suda.vim
function! suda#init(...) abort
  " ...
endfunction

function! suda#init_auto() abort
  let g:suda#prefix = 'suda://'
  call suda#init()
  " autocmd for normal files
  augroup suda_auto_internal
    autocmd BufReadCmd * call suda#YOUR_OPTIONAL_FEATURE_BufReadCmd()
    autocmd BufWriteCmd * call suda#YOUR_OPTIONAL_FEATURE_BufWriteCmd()
    " ...
  augroup END
endfunction

" plugin/suda.vim
if get(g:, 'suda_startup', 1)
  if get(g:, 'suda_automode')
  call suda#init_auto()
  else
  call suda#init()
  endif
endif
```

**Comment by doronbehar** [comment]
This seems rather too complicated IMO but I don't have enough experience to judge or suggest a better idea so I'll stick with this in the meantime.
