### ISSUE TITLE
Rename undescriptive name `suda#nopass` to more descriptive name like `suda#...something...`

### ISSUE THREAD

**Issue by lambdalisue** [lambdalisue/vim-suda#73]
From https://github.com/lambdalisue/suda.vim/issues/61#issuecomment-1990924321

First of all, we need to clarify the behavior of `suda#nopass` to find a good name for it.

**Comment by aarondill** [comment]
I wonder if we should change `suda#nopass` to force suda to give up if saving without a password doesn't work?

now we have the check if `sudo true` works, and then we try without a password, which removes much of the requirement for the current behavior of `suda#nopass`

**Comment by aarondill** [comment]
The only notable issue I could see with this approach would be using different values for `suda#executable`, where this would then mean that suda will *always* ask for a password if `suda#nopass` isn't set, and will *never* ask if `suda#nopass` is set.

this would eliminate support for commands that cache credentials, like sudo does; but our support for other values of `suda#executable` is extremely rudimentary anyways.

**Comment by sstark** [comment]
`suda#nopass` adds the flag --non-interactive (or rather its short form -n) to the call to sudo. So it could be called that: `suda#noninteractive`.

Or, since it introduces a risk to cause non-working setups, you could call it `suda#forcenoninteractive`

**Comment by lambdalisue** [comment]
`suda#noninteractive` (or `suda#non_interactive`) sounds good to me.
