### ISSUE TITLE
[suda] Vim(let):E730: Using a List as a String   

### ISSUE THREAD

**Issue by nemonein** [lambdalisue/vim-suda#77]
Hello.
I'm using vim(VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jan 29 2024 09:41:19)) on openwrt.
I installed suda.vim on vim, and I tried to `SudaWrite` I've got this message.

```
[suda] Vim(let):E730: Using a List as a String   
```
Any help would be appreciated.

**Comment by lambdalisue** [comment]
Reproduced. It works on Neovim but Vim. Downgrading suda.vim to https://github.com/lambdalisue/suda.vim/releases/tag/v1.1.0 may helps.

**Comment by lambdalisue** [comment]
We need to revert https://github.com/lambdalisue/suda.vim/pull/74 while Vim does not support a List `expr` but Neovim. 

fyi @aarondill 

##### Vim

```
system({expr} [, {input}])				*system()* *E677*
		Get the output of the shell command {expr} as a |String|.  See
		|systemlist()| to get the output as a |List|.

		When {input} is given and is a |String| this string is written
		to a file and passed as stdin to the command.  The string is
		written as-is, you need to take care of using the correct line
		separators yourself.
		If {input} is given and is a |List| it is written to the file
```

##### Neovim

```
system({cmd} [, {input}])                                        *system()* *E677*
		Note: Prefer |vim.system()| in Lua.

		Gets the output of {cmd} as a |string| (|systemlist()| returns
		a |List|) and sets |v:shell_error| to the error code.
		{cmd} is treated as in |jobstart()|:
		If {cmd} is a List it runs directly (no 'shell').
		If {cmd} is a String it runs in the 'shell', like this: >vim
		  call jobstart(split(&shell) + split(&shellcmdflag) + ['{cmd}'])

<		Not to be used for interactive commands.
```

**Comment by nemonein** [comment]
Thanks!

**Comment by aarondill** [comment]
@lambdalisue okay, i'm going to change the system to escape and join the string in `suda#systemlist` before passing it to `system` (sadly this means we have to use the intermediate shell)

**Comment by aarondill** [comment]
@nemonein can you test #78 to make sure it fixes this issue?

**Comment by nemonein** [comment]
@aarondill 
I tested in vim on openwrt, and it works fine.
Thank you very much.
