### ISSUE TITLE
Error executing system command when using nushell

### ISSUE THREAD

**Issue by glcraft** [lambdalisue/vim-suda#79]
Hi

I'm facing to an issue when I want to edit a file that needs suda to write and when I'm using [Nu shell](https://github.com/nushell/nushell).

suda prompts for the password when I try to write my file, and when I enter my password, I have the following message : 
```
[suda] Error: ^[[31mnu::parser::parse_mismatch^[[0m\n\n  ^[[31m×^[[0m Parse mismatch during operation.\n   ╭─[^[[36;1;4msource^[[0m:1:8]\n ^[[2m1^[[0m │ 'sudo' '-p' '' '-S' '--' 'dd' 'if=/tmp/nvim.gly/L1F4En/2' 'of=/etc/default/grub' 'bs=1048576'\n   · ^[[35;1m       ──┬─^[[0m\n   ·          ^[[35;1m╰── ^[[35;1mexpected operator^[[0m^[[0m\n   ╰────\n
```
Once formatted : 
```
Error: nu::parser::parse_mismatch

  × Parse mismatch during operation.
   ╭─[source:1:8]
 1 │ 'sudo' '-p' '' '-S' '--' 'dd' 'if=/tmp/nvim.gly/L1F4En/2' 'of=/etc/default/grub' 'bs=1048576'
   ·        ──┬─
   ·          ╰── expected operator
   ╰────
```
So it's happening because nushell does not support the executable written with simple quotes string like `'this'` (nor double quotes). 
![image](https://github.com/lambdalisue/suda.vim/assets/6421451/809fcb7e-7ebd-4557-a34f-44a2b1405c4f)

but Nushell does support executable with backticks, like `` `this` ``
![image](https://github.com/lambdalisue/suda.vim/assets/6421451/0caf6e59-6921-4454-bf30-aec475b36add)
(I did not execute the command in the picture, take my word for it :sweat_smile: )

**Comment by lambdalisue** [comment]
@glcraft Could you try if https://github.com/lambdalisue/suda.vim/pull/80 fix your issue?

**Comment by glcraft** [comment]
It works fine with this fix :+1:
