### ISSUE TITLE
"suda:" directories get added in current dir when saving

### ISSUE THREAD

**Issue by madhat2r** [lambdalisue/vim-suda#82]
I have a whole slew of "suda:" directories littering my filesystems.

It seems that whenever I open a restricted file and write to it there is a suda: directory written in the current working dir.

Is there a way to change this behavior? Perhaps set a default location for this dir like `/tmp`?

**Comment by lambdalisue** [comment]
Well, vim-suda doesn't have such feature. I think your configuration cause that problem.

**Comment by madhat2r** [comment]
This is my whole vim-suda config:
``` lua
return {
  "lambdalisue/suda.vim",
  lazy = false,
  -- cmd = { "SudaWrite", "SudaRead" },
  init = function() vim.g.suda_smart_edit = 1 end,
}
```

What do I need to change to make this different?

**Comment by lambdalisue** [comment]
I don’t believe the issue is related to Suda, so changing its configuration likely won’t help.

It’s just a guess, but some people have custom configurations in their vimrc that automatically create missing directories. Such a configuration might accidentally attempt to create a directory with a path like `suda://foo/bar/...`. If you have a similar setup, try disabling that configuration.

**Comment by madhat2r** [comment]
Thanks for the help @lambdalisue and sorry for the noise. 

It appears you might be correct, nvim will auto create missing dirs for me. Now I just need to find which plugin is doing this as I didn't install one specifically.

**Comment by pserey** [comment]
Sorry for reviving this solved issue! Just wanted to know if @madhat2r managed to find how to stop the directory creation. Had the same trouble with the suda directories lol

**Comment by madhat2r** [comment]
Hey @pserey, I did not find out what it is, but I was using AstoNvim distro and I suspect it was buried in that config somewhere, I just had no luck finding it. I have since moved away from AstroNvim, and I do not have that issue any longer.

**Comment by pserey** [comment]
Yeah, that's exactly my setup too lol. Thanks!
