### ISSUE TITLE
`setlocal nobackup` security fix affects all buffers

### ISSUE THREAD

**Issue by sevmonster** [lambdalisue/vim-suda#85]
With the implementation of #14, having any `suda://` buffer will [globally set `nobackup`](https://github.com/lambdalisue/vim-suda/blob/b97fab52f9cdeabe2bbb5eb98d82356899f30829/autoload/suda.vim#L189). This is because `backup` is global only and cannot be set buffer-local, and `setlocal` is the same as `set` when used with global options.

The more user-friendly way to do this would be to set `nobackup` as required before writing a `suda://` scheme buffer, and restore it to the previously set value afterward.

**Comment by lambdalisue** [comment]
I see. I'll fix that.

**Comment by sevmonster** [comment]
Thanks. For the record, I was incorrect. Removing `setlocal nobackup` was the correct choice of action. Even if `backup` is set, suda will not save a backup file if using `sudo` to write—nor will it with `:write` since it saves to a new filename every time.
