### ISSUE TITLE
Bad swap file load in `suda#read` silently blocks input

### ISSUE THREAD

**Issue by sevmonster** [lambdalisue/vim-suda#87]
When attempting to open a `suda://` scheme filename that is readable by the user, [the `suda#read` function `:execute`s `:read`](https://github.com/lambdalisue/vim-suda/blob/e333169211b84d6f4012ac9e40bcbbf370b74289/autoload/suda.vim#L104), which can trigger the processing of a swapfile. Should the swapfile cause an `E325: ATTENTION` message, the message will not be drawn properly for whatever reason, and Vim will wait for user input on what to do with the swapfile while showing a blank screen. The uninitiated may think Vim has hung or crashed.

If you enter any option but to recover the swapfile, `suda#read` will exit, and [all the options it later would set](https://github.com/lambdalisue/vim-suda/blob/e333169211b84d6f4012ac9e40bcbbf370b74289/autoload/suda.vim#L187) remain unset.

To fix this, `suda#read` should be called after `setlocal noswapfile`, if it's still intentional to not use swapfiles for `suda://` schemes.

I've fixed this in my environment by [setting `noswapfile` in a `BufReadPre` autocmd](https://github.com/lambdalisue/vim-suda/issues/25#issuecomment-2521351030). Additionally, enabling the swapfile later in the `BufReadPre` will show the error at least somewhat correctly.

**Comment by lambdalisue** [comment]
Thanks. Could you try #88 ?

**Comment by sevmonster** [comment]
yes, #88 resolves the issue for me. thanks!
