### ISSUE TITLE
Cache credentials like sudo

### ISSUE THREAD

**Issue by tyilo** [lambdalisue/vim-suda#9]
The following shell code will probably only ask the user for their password once (at least with default sudo configurations):
```
sudo id
sudo id
```

However doing `:w suda://%` twice will always ask for the users password twice.

Is it possible to make suda cache credentials like sudo?

**Comment by lambdalisue** [comment]
It's neovim's bug.
https://github.com/lambdalisue/suda.vim/pull/3#issuecomment-404900005
